bind-address = "0.0.0.0"
port = 8086
reporting-disabled = false

[meta]
  dir = "/var/opt/influxdb/meta"

[initialization]
  join-urls = ""

[authentication]
  enabled = false

[admin]
  enabled = true
  port = 8083
  assets = "/opt/influxdb/current/admin"

[api]
  bind-address = "0.0.0.0"
  port = 8086

[[graphite]]
  enabled = true
  batch-size = 1000 # will flush if this many points get buffered
  batch-pending = 5 # number of batches that may be pending in memory
  batch-timeout = "1s" # will flush at least this often even if we haven't hit buffer limit

[collectd]
  enabled = false

[opentsdb]
  enabled = false

[udp]
  enabled = false

[broker]
  dir = "/data/broker"
  enabled = true
  election-timeout = "0"

[data]
  dir = "/data/db"
  enabled = true
  retention-auto-create = true
  retention-check-enabled = true
  retention-check-period = "10m0s"
  retention-create-period = "45m0s"

[snapshot]
  enabled = false

[logging]
  write-tracing = false
  raft-tracing = false
  level  = "info"
  file   = "/opt/influxdb/shared/log.txt"

[monitoring]
  enabled = true

[debugging]
  pprof-enabled = false

[continuous_queries]
  recompute-previous-n = 2
  recompute-no-older-than = "10m0s"
  compute-runs-per-interval = 10
  compute-no-more-than = "2m0s"
  disabled = false

[hinted-handoff]
  enabled = true
  dir = "/var/opt/influxdb/hh"
